"""
Language-dependent intent patterns (data only).

Kept separate from `modules/intent_engine.py` so the engine logic stays DRY and
language packs can evolve without touching classification code.
"""

# ============================================================================
# ENGLISH INTENT PATTERNS
# ============================================================================

INTENT_PATTERNS_EN = {
    'play_music': {
        'triggers': [
            'play',
            'play song',
            'play music',
            'can you play',
            'could you play',
            'put on',
            'start playing',
            'i want to listen',
            'i want to hear',
        ],
        'extract': r'(?:play|put on|start playing|can you play|could you play|i want to (?:listen|hear)(?: to)?)\s+(?:to\s+)?(.+)',
        'priority': 10,
    },
    'play_favorites': {
        'triggers': [
            'play my favorites',
            'play favorites',
            'play my favourite',
            'play favourite',
            'play what i like',
        ],
        'extract': None,
        'priority': 5,
    },
    'pause': {
        'triggers': [
            'pause',
            'pause music',
            'pause song',
            'pause playback',
        ],
        'extract': None,
        'priority': 10,
    },
    'resume': {
        'triggers': [
            'resume',
            'continue',
            'unpause',
            'keep playing',
            'start again',
        ],
        'extract': None,
        'priority': 10,
    },
    'stop': {
        'triggers': [
            'stop',
            'stop music',
            'stop playing',
            'turn off',
        ],
        'extract': None,
        'priority': 10,
    },
    'next': {
        'triggers': [
            'next',
            'next song',
            'next track',
            'skip',
            'skip song',
            'skip this',
        ],
        'extract': None,
        'priority': 10,
    },
    'previous': {
        'triggers': [
            'previous',
            'previous song',
            'previous track',
            'go back',
            'back',
            'last song',
        ],
        'extract': None,
        'priority': 10,
    },
    'volume_up': {
        'triggers': [
            'louder',
            'volume up',
            'turn it up',
            'increase volume',
            'raise volume',
        ],
        'extract': None,
        'priority': 10,
    },
    'volume_down': {
        'triggers': [
            'quieter',
            'volume down',
            'turn it down',
            'decrease volume',
            'lower volume',
            'lower the volume',
        ],
        'extract': None,
        'priority': 10,
    },
    'set_volume': {
        'triggers': [
            'set volume to 50',
            'set volume to 80',
            'volume to 60',
            'set volume 70',
            'adjust volume to 40',
            'volume 50',
            'set to 50',
            'volume level 60',
            'sound to 50',
            'set sound to 60',
        ],
        'extract': r'(?:set|adjust|volume|sound)\s+(?:the\s+)?(?:volume|sound|to)?\s*(?:to\s+)?(\d+)',
        'priority': 20,
    },
    'add_favorite': {
        'triggers': [
            'i love this',
            'i love this song',
            'love this',
            'like this',
            'like this song',
            'add to favorites',
            'add to favourites',
            'favorite this',
            'favourite this',
            'save this',
            'save this song',
        ],
        'extract': None,
        'priority': 10,
    },
    'sleep_timer': {
        'triggers': [
            'stop in 30 minutes',
            'stop in 15 minutes',
            'stop in 60 minutes',
            'turn off in 30 minutes',
            'sleep timer 30 minutes',
            'set sleep timer',
            'set timer',
        ],
        'extract': r'(?:stop|turn off|timer)\s+(?:in\s+)?(\d+)\s*(?:minute|min)',
        'priority': 20,
    },
    'repeat_song': {
        'triggers': [
            'repeat this',
            'repeat this song',
            'play this again',
            'play this on repeat',
            'keep repeating',
            'loop this',
            'loop this song',
        ],
        'extract': None,
        'priority': 10,
    },
    'repeat_off': {
        'triggers': [
            'stop repeating',
            'turn off repeat',
            'no more repeat',
            'repeat off',
            'stop looping',
        ],
        'extract': None,
        'priority': 10,
    },
    'shuffle_on': {
        'triggers': [
            'shuffle',
            'turn on shuffle',
            'shuffle mode',
            'play random',
            'random songs',
            'mix it up',
        ],
        'extract': None,
        'priority': 10,
    },
    'shuffle_off': {
        'triggers': [
            'stop shuffle',
            'turn off shuffle',
            'no shuffle',
            'shuffle off',
            'play in order',
        ],
        'extract': None,
        'priority': 10,
    },
    'play_next': {
        'triggers': [
            'play frozen next',
            'play beatles next',
            'next play frozen',
            'add frozen to next',
        ],
        'extract': r'(?:play|next|add)\s+(.+?)\s+(?:next|after this)',
        'priority': 15,
    },
    'add_to_queue': {
        'triggers': [
            'add frozen to queue',
            'add beatles',
            'queue frozen',
            'add to playlist',
        ],
        'extract': r'(?:add|queue)\s+(.+?)(?:\s+to\s+(?:queue|playlist))?',
        'priority': 10,
    },
    'set_alarm': {
        'triggers': [
            'wake me up at 7',
            'set alarm for 7 am',
            'wake me at 7 with frozen',
            'alarm at 7',
            'morning alarm 7 am',
        ],
        'extract': r'(?:wake|alarm)\s+(?:me\s+)?(?:up\s+)?(?:at\s+|for\s+)?(\d{1,2}(?::\d{2})?(?:\s*(?:am|pm))?)',
        'priority': 15,
    },
    'cancel_alarm': {
        'triggers': [
            'cancel alarm',
            'cancel my alarm',
            'turn off alarm',
            'no alarm',
            'delete alarm',
        ],
        'extract': None,
        'priority': 10,
    },
    'check_bedtime': {
        'triggers': [
            'what is my bedtime',
            'when is bedtime',
            'what time is bedtime',
            'when do i go to bed',
            'check bedtime',
        ],
        'extract': None,
        'priority': 10,
    },
    'check_time_limit': {
        'triggers': [
            'how much time left',
            'how much time do i have',
            'time remaining',
            'check my time',
            'how long can i listen',
        ],
        'extract': None,
        'priority': 10,
    },
    'set_bedtime': {
        'triggers': [
            'set bedtime to 9 pm',
            'change bedtime to 9',
            'bedtime at 9',
            'make bedtime 9 pm',
        ],
        'extract': r'(?:set|change|make)\s+bedtime\s+(?:to\s+|at\s+)?(\d{1,2}(?::\d{2})?(?:\s*(?:am|pm))?)',
        'priority': 15,
    },
}


# ============================================================================
# FRENCH INTENT PATTERNS
# ============================================================================

INTENT_PATTERNS_FR = {
    'play_music': {
        'triggers': [
            'joue',
            'joue chanson',
            'joue musique',
            'mets',
            'mettre',
            'lance',
            'joue moi',
            'mets moi',
            'mets-moi',
            'fais jouer',
            'fais moi écouter',
            'fais-moi écouter',
            'est ce que tu peux jouer',
            'est ce que tu peux mettre',
            'pourrais tu jouer',
            'pourrais tu mettre',
            'tu pourrais jouer',
            'tu pourrais mettre',
            'tu veux bien jouer',
            'tu veux bien mettre',
            'je veux que tu joues',
            'je veux que tu mettes',
            "j'ai envie d'écouter",
            "j'ai envie d'entendre",
            'tu peux jouer',
            'tu peux mettre',
            'peux tu jouer',
            'peux tu mettre',
            'peux jouer',
            'peux mettre',
            'mets la chanson',
            'je veux écouter',
            'je veux ecouter',
            'je veux entendre',
            'je voudrais écouter',
            'je voudrais ecouter',
            "j'aimerais ecouter",
            "j'aimerais écouter",
            "j'aimerais entendre",
            'je vais écouter',
        ],
        'extract': (
            r'(?:'
            r'joue|mets|mettre|lance|'
            r'fais\s+(?:moi\s+)?(?:jouer|écouter|ecouter)|'
            r'est\s+ce\s+que\s+tu\s+peux\s+(?:jouer|mettre)|'
            r'(?:pourrais\s+tu|tu\s+pourrais)\s+(?:jouer|mettre)|'
            r'tu\s+veux\s+bien\s+(?:jouer|mettre)|'
            r'je\s+veux\s+que\s+tu\s+(?:joues|mettes)|'
            r"j(?:'| )ai\s+envie\s+d(?:'|e)\s*(?:écouter|ecouter|entendre)|"
            r'tu\s+peux\s+(?:jouer|mettre)|'
            r'peux\s+(?:tu\s+)?(?:jouer|mettre)|'
            r'je\s+(?:veux|voudrais|vais)\s+(?:écouter|ecouter|entendre)|'
            r"j'aimerais\s+(?:écouter|ecouter|entendre)"
            r')\s+(?:moi\s+)?(.+)'
        ),
        'priority': 10,
    },
    'play_favorites': {
        'triggers': [
            'joue mes favoris',
            'joue mes préférés',
            'joue mes preferes',
            "joue ce que j'aime",
            "joue ce que j aime",
            'joue favoris',
            'mes favoris',
            'mes préférés',
            'mes preferes',
            'mets mes favoris',
            'mets mes préférés',
            'mets mes preferes',
            'lance mes favoris',
            'favoris',
            'préférés',
            'preferes',
            'mes chansons préférées',
            'mes chansons preferees',
            "ce que j'aime",
            "ce que j aime",
            'mes musiques préférées',
            'mes musiques preferees',
        ],
        'extract': None,
        'priority': 15,  # Higher than play_music to win disambiguation
    },
    'pause': {
        'triggers': [
            'pause',
            'mets en pause',
            'mets pause',
            'met en pause',
            'met pause',
            'pause la musique',
            'pause chanson',
            'fais une pause',
            'arrête temporairement',
            'arrete temporairement',
            'stop temporaire',
            'attend',
            'attends',
            'patiente',
        ],
        'extract': None,
        'priority': 10,
    },
    'resume': {
        'triggers': [
            'reprends',
            'reprend',
            'continue',
            'continues',
            'relance',
            'enlève la pause',
            'enleve la pause',
            'retire la pause',
            'redémarre',
            'redemarre',
            'remet la musique',
            'remets la musique',
            'rejoue',
            'recommence',
            'reprends la musique',
            'reprend la musique',
            'c\'est bon',
            'c est bon',
            'vas-y',
            'vas y',
        ],
        'extract': None,
        'priority': 10,
    },
    'stop': {
        'triggers': [
            'arrête',
            'arrete',
            'arrêter',
            'arreter',
            'stop',
            'arrête la musique',
            'arrete la musique',
            'arrête de jouer',
            'arrete de jouer',
            'arrête tout',
            'arrete tout',
            'éteins',
            'eteins',
            'éteins la musique',
            'eteins la musique',
            'éteins tout',
            'eteins tout',
            'coupe',
            'coupe la musique',
            'termine',
            'fini',
            'finis',
            'silence',
            'tais-toi',
            'tais toi',
        ],
        'extract': None,
        'priority': 10,
    },
    'next': {
        'triggers': [
            'suivant',
            'suivante',
            'suivants',
            'chanson suivante',
            'piste suivante',
            'musique suivante',
            'morceau suivant',
            'passe',
            'passe à la suivante',
            'passe a la suivante',
            'passe suivant',
            'skip',
            'saute',
            'saute celle-ci',
            'saute celle ci',
            'change',
            'change de chanson',
            'change de musique',
            'autre',
            'une autre',
            'prochaine',
            'prochain',
            'après',
            'apres',
            "j'aime pas",
            "j aime pas",
        ],
        'extract': None,
        'priority': 10,
    },
    'previous': {
        'triggers': [
            'précédent',
            'precedent',
            'précédente',
            'precedente',
            'chanson précédente',
            'chanson precedente',
            'piste précédente',
            'piste precedente',
            'musique précédente',
            'musique precedente',
            'morceau précédent',
            'morceau precedent',
            'retour',
            'retour arrière',
            'retour arriere',
            'reviens en arrière',
            'reviens en arriere',
            'avant',
            'd\'avant',
            'd avant',
            'dernière chanson',
            'derniere chanson',
            'dernière',
            'derniere',
            'remet la précédente',
            'remet la precedente',
            'rejoue la dernière',
            'rejoue la derniere',
        ],
        'extract': None,
        'priority': 10,
    },
    'volume_up': {
        'triggers': [
            'plus fort',
            'monte le volume',
            'monte volume',
            'augmente',
            'augmente le volume',
            'augmente le son',
            'augmente volume',
            'plus de volume',
            'monte',
            'monte le son',
            'plus haut',
            'plus de son',
            'un peu plus fort',
            'encore plus fort',
            'plus',
            "j'entends pas",
            "j entends pas",
            "j'entends mal",
            "j entends mal",
            'on entend rien',
            'trop bas',
            'pousse',
            'pousse le son',
            'pousse le volume',
        ],
        'extract': None,
        'priority': 10,
    },
    'volume_down': {
        'triggers': [
            'moins fort',
            'baisse le volume',
            'baisse volume',
            'diminue',
            'diminue le volume',
            'diminue le son',
            'diminue volume',
            'moins de volume',
            'baisse',
            'baisse le son',
            'plus bas',
            'moins de son',
            'un peu moins fort',
            'encore moins fort',
            'moins',
            'trop fort',
            'c\'est trop fort',
            'c est trop fort',
            'mes oreilles',
            'doucement',
            'plus doucement',
            'chut',
            'chuchote',
        ],
        'extract': None,
        'priority': 10,
    },
    'set_volume': {
        'triggers': [
            'mets le volume à 50',
            'mets le volume à 80',
            'mets le volume à 0',
            'mets le volume à 100',
            'mets le volume à 75',
            'volume à 60',
            'mets volume à 70',
            'règle le volume à 40',
            'règle volume à 90',
            'regle le volume à 90',
            'mets à 50',
            'volume 50',
            'niveau sonore à 60',
            'niveau de volume à 70',
            'ajuste le volume à 80',
            'son à 50',
            'mets son à 60',
            'monte le volume à 80',
            'baisse le volume à 20',
            'volume à cinquante',
            'volume à soixante',
            'volume à quatre-vingts',
            'volume à quatre vingts',
            'mets le volume à cinquante',
            'mets le volume à soixante',
            'mets le volume à quatre vingts',
            'mets à cinquante',
            'mets à soixante',
            'mets à quatre-vingts',
            'mets à quatre vingts',
        ],
        'extract': r'(?:mets|règle|regle|ajuste|monte|baisse|met|volume|son)\s+(?:le\s+)?(?:volume|son|niveau|à|a)?\s*(?:à|a)\s+(\d+|cinquante|soixante|soixante-dix|soixante\s+dix|quatre-vingts?|quatre\s+vingts?|cent)',
        'priority': 25,
    },
    'add_favorite': {
        'triggers': [
            "j'adore",
            "j adore",
            "j'adore ça",
            "j adore ça",
            "j adore ca",
            "j'aime",
            "j aime",
            "j'aime cette chanson",
            "j aime cette chanson",
            "j'aime ça",
            "j aime ça",
            "j aime ca",
            "j'aime bien",
            "j aime bien",
            "j'aime beaucoup",
            "j aime beaucoup",
            'ajoute aux favoris',
            'ajoute aux préférés',
            'ajoute aux preferes',
            'mets dans les favoris',
            'mets dans mes favoris',
            'mets aux favoris',
            'favori',
            'sauvegarde',
            'garde ça',
            'garde ça dans mes favoris',
            'garde ca',
            'enregistre',
            'enregistre ça',
            'enregistre ca',
            'mets en favori',
            "c'est ma préférée",
            "c est ma preferee",
            "c'est mon préféré",
            "c est mon prefere",
            'trop bien',
            'génial',
            'genial',
            'super',
        ],
        'extract': None,
        'priority': 10,
    },
    'sleep_timer': {
        'triggers': [
            'arrête dans 30 minutes',
            'arrête dans 15 minutes',
            'arrête dans 60 minutes',
            'arrête dans une demi-heure',
            'éteins dans 30 minutes',
            'éteins dans 5 minutes',
            'stop dans 20 minutes',
            'stop dans 30 minutes',
            'minuterie 30 minutes',
            'mets une minuterie',
            'minuterie de sommeil',
        ],
        'extract': r'(?:arrête|arrete|éteins|eteins|stop|minuterie)\s+(?:dans\s+|de\s+)?(\d+|une\s+demi-heure|demi-heure|demie\s+heure)\s*(?:minute|min)?',
        'priority': 20,
    },
    'repeat_song': {
        'triggers': [
            'répète',
            'repete',
            'répète ça',
            'repete ça',
            'repete ca',
            'répète cette chanson',
            'repete cette chanson',
            'rejoue ça',
            'rejoue ca',
            'rejoue cette chanson',
            'mets en boucle',
            'met en boucle',
            'en boucle',
            'mode boucle',
            'encore une fois',
            'recommence la chanson',
            'refais',
            'refais ça',
            'refais ca',
            'remet la même',
            'remet la meme',
            'la même chanson',
            'la meme chanson',
        ],
        'extract': None,
        'priority': 15,  # Higher to win over resume
    },
    'repeat_off': {
        'triggers': [
            'arrête de répéter',
            'arrete de repeter',
            'enlève la répétition',
            'enleve la repetition',
            'plus de répétition',
            'plus de repetition',
            'répétition off',
            'repetition off',
            'enlève la boucle',
            'enleve la boucle',
            'stop répéter',
            'stop repeter',
            'arrête la boucle',
            'arrete la boucle',
            'boucle off',
            'mode normal musique',
            'joue normalement',
        ],
        'extract': None,
        'priority': 18,  # Very high to win over generic "stop"
    },
    'shuffle_on': {
        'triggers': [
            'mélange',
            'melange',
            'aléatoire',
            'aleatoire',
            'mode aléatoire',
            'mode aleatoire',
            'joue au hasard',
            'au hasard',
            'mixe',
            'mixe tout',
            'mélange tout',
            'melange tout',
            'hasard',
            'random',
            'aléa',
            'alea',
            'shuffle on',
            'active shuffle',
            'mode shuffle',
            'mélange les chansons',
            'melange les chansons',
        ],
        'extract': None,
        'priority': 15,  # Higher to disambiguate
    },
    'shuffle_off': {
        'triggers': [
            'arrête de mélanger',
            'arrete de melanger',
            "plus d'aléatoire",
            "plus d aleatoire",
            'aléatoire off',
            'aleatoire off',
            'en ordre',
            "dans l'ordre",
            "dans l ordre",
            'ordre normal musique',
            'stop mélanger',
            'stop melanger',
            'stop shuffle',
            'désactive shuffle',
            'desactive shuffle',
            'shuffle off',
            'pas de shuffle',
            'pas aléatoire',
            'pas aleatoire',
            'joue normalement',
        ],
        'extract': None,
        'priority': 18,  # Very high to win over generic "stop"
    },
    'play_next': {
        'triggers': [
            'joue frozen ensuite',
            'joue beatles après',
            'suivant frozen',
            'après joue frozen',
            'mets frozen après',
        ],
        'extract': r'(?:joue|mets|suivant)\s+(.+?)\s+(?:ensuite|après)',
        'priority': 15,
    },
    'add_to_queue': {
        'triggers': [
            'ajoute frozen',
            'ajoute beatles',
            'ajoute à la file',
            "file d'attente frozen",
            'ajoute à la playlist',
        ],
        'extract': r'(?:ajoute|file)\s+(?:d\'attente\s+)?(.+?)(?:\s+(?:à la file|à la playlist))?',
        'priority': 10,
    },
    'set_alarm': {
        'triggers': [
            'réveille-moi à 7',
            'réveille moi à 7',
            'alarme à 7 heures',
            'mets une alarme',
            'alarme pour 7',
            'réveille-moi à 7 avec frozen',
        ],
        'extract': r'(?:réveille|alarme)\s+(?:moi\s+)?(?:à\s+|pour\s+)?(\d{1,2}(?::\d{2})?(?:\s*(?:h|heures?))?)',
        'priority': 15,
    },
    'cancel_alarm': {
        'triggers': [
            "annule l'alarme",
            'annule alarme',
            "enlève l'alarme",
            "pas d'alarme",
            'supprime alarme',
        ],
        'extract': None,
        'priority': 10,
    },
    'check_bedtime': {
        'triggers': [
            "c'est quand l'heure du coucher",
            'quelle est mon heure de coucher',
            'quand je vais au lit',
            "c'est quand mon coucher",
            'heure de coucher',
        ],
        'extract': None,
        'priority': 10,
    },
    'check_time_limit': {
        'triggers': [
            'combien de temps il reste',
            "combien de temps j'ai",
            'temps restant',
            'mon temps restant',
            'combien je peux écouter',
        ],
        'extract': None,
        'priority': 10,
    },
    'set_bedtime': {
        'triggers': [
            "mets l'heure du coucher à 21",
            "change l'heure du coucher",
            'coucher à 21 heures',
            'heure de coucher 21',
        ],
        'extract': r'(?:mets|change)\s+(?:l\')?heure\s+(?:du\s+)?coucher\s+(?:à\s+)?(\d{1,2}(?::\d{2})?(?:\s*(?:h|heures?))?)',
        'priority': 15,
    },
}


# ============================================================================
# LANGUAGE REGISTRY
# ============================================================================

LANGUAGE_PATTERNS = {
    'en': INTENT_PATTERNS_EN,
    'fr': INTENT_PATTERNS_FR,
}

# Production intent scope: Essential commands for kids
# Core playback + volume control + favorites
ACTIVE_INTENTS = {
    # Simplified intent set (only 4 intents)
    'play_music',    # Play any music by name
    'volume_up',     # Increase volume
    'volume_down',   # Decrease volume
    'stop',          # Stop playback

    # Note: Shuffle and repeat are enabled by default in config.py
    # - DEFAULT_SHUFFLE_MODE = 'true'
    # - DEFAULT_REPEAT_MODE = 'playlist'
    # Continuous playback happens automatically
}
